name: Build Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Create env.env file
        shell: bash
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          touch neodeemer/env.env
          echo SPOTIPY_CLIENT_ID="$SPOTIPY_CLIENT_ID" >> neodeemer/env.env
          echo SPOTIPY_CLIENT_SECRET="$SPOTIPY_CLIENT_SECRET" >> neodeemer/env.env
          echo YOUTUBE_API_KEY="$YOUTUBE_API_KEY" >> neodeemer/env.env

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('neodeemer/buildozer.spec') }}

      #- name: Cache Buildozer local directory
      #  uses: actions/cache@v3
      #  with:
      #    path: neodeemer/.buildozer
      #    key: buildozer-local-${{ hashFiles('neodeemer/buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          command: >
            pip3 install yt_dlp --target /github/workspace/neodeemer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/neodeemer/armeabi-v7a/;
            pip3 install yt_dlp --target /github/workspace/neodeemer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/neodeemer/arm64-v8a/;
            cd /github/workspace/neodeemer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/neodeemer/armeabi-v7a/yt_dlp/extractor/;
            mkdir ../temp/;
            mv __init__.py _extractors.py extractors.py youtube.py ../temp/;
            rm -r *; cd ../temp/; mv __init__.py _extractors.py extractors.py youtube.py ../extractor/;
            cd /github/workspace/neodeemer/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/neodeemer/arm64-v8a/yt_dlp/extractor/;
            mkdir ../temp/;
            mv __init__.py _extractors.py extractors.py youtube.py ../temp/;
            rm -r *; cd ../temp/; mv __init__.py _extractors.py extractors.py youtube.py ../extractor/;
            pip3 install sh==1.14.2; cd /github/workspace/neodeemer; buildozer android debug
          workdir: neodeemer

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ${{ steps.buildozer.outputs.filename }}